openapi: "3.0.2"
info:
  version: 1.0.0
  title: m8flow-backend-extension
paths:
  /create-tenant:
    post:
      summary: Create a new tenant
      operationId: m8flow_backend.routes.tenant_controller.create_tenant
      tags:
        - Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTenantRequest"
      responses:
        "201":
          description: Tenant created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantResponse"
        "400":
          description: Bad request - missing required fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized - user not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Conflict - tenant with ID or slug already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tenant-login-url:
    get:
      summary: Get Keycloak login URL for a tenant realm (unauthenticated)
      description: Checks Keycloak for the tenant realm; if it exists returns the authorization URL for that realm.
      operationId: m8flow_backend.routes.keycloak_controller.get_tenant_login_url
      tags:
        - Keycloak
      security: []
      parameters:
        - name: tenant
          in: query
          required: true
          schema:
            type: string
          description: Tenant (realm) name to look up in Keycloak
      responses:
        "200":
          description: Tenant realm exists; login URL returned
          content:
            application/json:
              schema:
                type: object
                required:
                  - login_url
                properties:
                  login_url:
                    type: string
                    description: Keycloak authorization (login) base URL for the tenant realm
                  realm:
                    type: string
                    description: Realm name
        "400":
          description: Bad request - tenant missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        "404":
          description: Tenant realm not found in Keycloak
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string

  /tenants/check:
    get:
      summary: Check if tenant exists by slug or id (unauthenticated)
      description: For pre-login tenant selection. Only considers ACTIVE tenants.
      operationId: m8flow_backend.routes.tenant_controller.check_tenant_exists
      tags:
        - Tenant
      security: []
      parameters:
        - name: identifier
          in: query
          required: true
          schema:
            type: string
          description: Tenant slug or id to look up
      responses:
        "200":
          description: Check result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantExistsResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tenants/slug/{slug}:
    get:
      summary: Get tenant by slug
      operationId: m8flow_backend.routes.tenant_controller.get_tenant_by_slug
      tags:
        - Tenant
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Human-readable slug identifier of the tenant
      responses:
        "200":
          description: Tenant retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantResponse"
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot access default tenant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Tenant not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tenants:
    get:
      summary: Get all tenants
      operationId: m8flow_backend.routes.tenant_controller.get_all_tenants
      tags:
        - Tenant
      responses:
        "200":
          description: List of all tenants
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantListResponse"
        "401":
          description: Unauthorized - user not authenticated
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tenants/{tenant_id}:
    get:
      summary: Get tenant by ID
      operationId: m8flow_backend.routes.tenant_controller.get_tenant_by_id
      tags:
        - Tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the tenant
      responses:
        "200":
          description: Tenant retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantResponse"
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot access default tenant
        "404":
          description: Tenant not found

    put:
      summary: Update a tenant
      description: Updates tenant name and/or status. Slug cannot be updated. Cannot update DELETED tenants.
      operationId: m8flow_backend.routes.tenant_controller.update_tenant
      tags:
        - Tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the tenant to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: New name for the tenant
                status:
                  type: string
                  enum: [ACTIVE, INACTIVE, DELETED]
                  description: New status for the tenant
              example:
                name: "Updated Tenant Name"
                status: "ACTIVE"
      responses:
        "200":
          description: Tenant updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "400":
          description: Bad request - no fields to update, slug update attempted, tenant is deleted, or invalid status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot update default tenant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Tenant not found
        "500":
          description: Internal server error

    delete:
      summary: Soft delete a tenant
      description: Sets the tenant status to DELETED without removing from database
      operationId: m8flow_backend.routes.tenant_controller.delete_tenant
      tags:
        - Tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the tenant to delete
      responses:
        "200":
          description: Tenant soft deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "400":
          description: Bad request - tenant already deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot delete default tenant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Tenant not found
        "500":
          description: Internal server error

components:
  schemas:
    CreateTenantRequest:
      type: object
      required:
        - name
        - slug
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string

    Tenant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedBy:
          type: string

    TenantResponse:
      $ref: "#/components/schemas/Tenant"

    TenantListResponse:
      type: array
      items:
        $ref: "#/components/schemas/Tenant"

    TenantExistsResponse:
      type: object
      required:
        - exists
      properties:
        exists:
          type: boolean
          description: Whether an active tenant with the given slug or id exists
        tenant_id:
          type: string
          description: Canonical tenant id when exists is true (for storage/headers)

    TenantActionData:
      type: object
      properties:
        message:
          type: string
        tenant:
          $ref: "#/components/schemas/Tenant"

    TenantActionResponse:
      $ref: "#/components/schemas/TenantActionData"

    MessageData:
      type: object
      properties:
        message:
          type: string

    MessageResponse:
      $ref: "#/components/schemas/MessageData"

    ErrorData:
      type: object
      properties:
        error_code:
          type: string
        message:
          type: string

    ErrorResponse:
      $ref: "#/components/schemas/ErrorData"
