openapi: "3.0.2"
info:
  version: 1.0.0
  title: m8flow-backend-extension
paths:
  /create-tenant:
    post:
      summary: Create a new tenant
      operationId: m8flow_backend.routes.tenant_controller.create_tenant
      tags:
        - Tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTenantRequest"
      responses:
        "201":
          description: Tenant created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tenant"
        "400":
          description: Bad request - missing required fields
        "401":
          description: Unauthorized - user not authenticated
        "409":
          description: Conflict - tenant with slug already exists

  /tenants/slug/{slug}:
    get:
      summary: Get tenant by slug
      operationId: m8flow_backend.routes.tenant_controller.get_tenant_by_slug
      tags:
        - Tenant
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          description: Human-readable slug identifier of the tenant
      responses:
        "200":
          description: Tenant retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tenant"
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot access default tenant
        "404":
          description: Tenant not found

  /tenants:
    get:
      summary: Get all tenants
      operationId: m8flow_backend.routes.tenant_controller.get_all_tenants
      tags:
        - Tenant
      responses:
        "200":
          description: List of all tenants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tenant"
        "401":
          description: Unauthorized - user not authenticated
        "500":
          description: Internal server error

  /tenants/{tenant_id}:
    get:
      summary: Get tenant by ID
      operationId: m8flow_backend.routes.tenant_controller.get_tenant_by_id
      tags:
        - Tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the tenant
      responses:
        "200":
          description: Tenant retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tenant"
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot access default tenant
        "404":
          description: Tenant not found

    put:
      summary: Update a tenant
      description: Updates tenant name and/or status. Slug cannot be updated. Cannot update DELETED tenants.
      operationId: m8flow_backend.routes.tenant_controller.update_tenant
      tags:
        - Tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the tenant to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: New name for the tenant
                status:
                  type: string
                  enum: [ACTIVE, INACTIVE, DELETED]
                  description: New status for the tenant
              example:
                name: "Updated Tenant Name"
                status: "ACTIVE"
      responses:
        "200":
          description: Tenant updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Tenant 'Updated Tenant Name' has been successfully updated."
                  tenant:
                    $ref: "#/components/schemas/Tenant"
        "400":
          description: Bad request - no fields to update, slug update attempted, tenant is deleted, or invalid status
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot update default tenant
        "404":
          description: Tenant not found
        "500":
          description: Internal server error
    
    delete:
      summary: Soft delete a tenant
      description: Sets the tenant status to DELETED without removing from database
      operationId: m8flow_backend.routes.tenant_controller.delete_tenant
      tags:
        - Tenant
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the tenant to delete
      responses:
        "200":
          description: Tenant soft deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Tenant 'Example Tenant' has been successfully deleted."
                  tenant:
                    $ref: "#/components/schemas/Tenant"
        "400":
          description: Bad request - tenant already deleted
        "401":
          description: Unauthorized - user not authenticated
        "403":
          description: Forbidden - cannot delete default tenant
        "404":
          description: Tenant not found
        "500":
          description: Internal server error

components:
  schemas:
    CreateTenantRequest:
      type: object
      required:
        - id
        - name
        - slug
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE, DELETED]

    Tenant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
        created_by:
          type: string
        modified_by:
          type: string
