"""add_template_table

Revision ID: 0003
Revises: 0002
Create Date: 2026-01-15 11:56:30.471226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('m8f_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('bpmn_object_key', sa.String(length=1024), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('m8f_tenant_id', 'template_key', 'version', name='uq_template_key_version_tenant')
    )
    op.create_index('ix_template_is_published', 'template', ['is_published'], unique=False)
    op.create_index('ix_template_m8f_tenant_id', 'template', ['m8f_tenant_id'], unique=False)
    op.create_index('ix_template_status', 'template', ['status'], unique=False)
    op.create_index('ix_template_template_key', 'template', ['template_key'], unique=False)
    op.create_index('ix_template_visibility', 'template', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_template_visibility', table_name='template')
    op.drop_index('ix_template_template_key', table_name='template')
    op.drop_index('ix_template_status', table_name='template')
    op.drop_index('ix_template_m8f_tenant_id', table_name='template')
    op.drop_index('ix_template_is_published', table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
