"""Add m8flow_nats_tokens table

Revision ID: b8837274af96
Revises: f6a7b8c9d0e1
Create Date: 2026-03-12 13:07:44.681299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8837274af96'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m8flow_nats_tokens',
    sa.Column('m8f_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['m8f_tenant_id'], ['m8flow_tenant.id'], ),
    sa.PrimaryKeyConstraint('m8f_tenant_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_m8flow_process_model_template_m8f_tenant_id'), 'm8flow_process_model_template', ['m8f_tenant_id'], unique=False)
    op.alter_column('m8flow_templates', 'files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(op.f('uq_m8flow_tenant_slug'), 'm8flow_tenant', type_='unique')
    op.drop_index(op.f('ix_m8flow_tenant_slug'), table_name='m8flow_tenant')
    op.create_index(op.f('ix_m8flow_tenant_slug'), 'm8flow_tenant', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m8flow_tenant_slug'), table_name='m8flow_tenant')
    op.create_index(op.f('ix_m8flow_tenant_slug'), 'm8flow_tenant', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_m8flow_tenant_slug'), 'm8flow_tenant', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('m8flow_templates', 'files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_m8flow_process_model_template_m8f_tenant_id'), table_name='m8flow_process_model_template')
    op.drop_table('m8flow_nats_tokens')
    # ### end Alembic commands ###
