# syntax=docker/dockerfile:1
# m8flow-connector-proxy/dev.Dockerfile
# Local-dev image for the connector proxy: installs the project's real
# dependencies (matching poetry.lock exactly) and runs Flask's own dev server
# (bin/run_server_locally) instead of gunicorn. Single-stage and never pushed
# anywhere -- the deployment image is Dockerfile.
#
# Build from the REPO ROOT, not this directory -- same context Dockerfile
# uses -- because pyproject.toml's `m8flow-telemetry = { path =
# "../m8flow-telemetry" }` dependency needs that sibling directory available:
#   docker build -f m8flow-connector-proxy/dev.Dockerfile -t m8flow-connector-proxy:dev .
#   docker run --rm -it -p 7004:7004 m8flow-connector-proxy:dev
#
# poetry is pinned to match poetry.lock's own generator (see the "generated by
# Poetry X.Y.Z" line at the top of the lock file) -- an older poetry can fail
# to read a newer lock-file format, so keep these in sync if the lock is
# regenerated with a different poetry version.

FROM python:3.12.1-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install poetry==2.2.1 pytest-xdist==3.5.0 \
    && poetry config virtualenvs.create false

RUN apt-get update \
  && apt-get install -y -q --no-install-recommends gcc libssl-dev pkg-config \
  && rm -rf /var/lib/apt/lists/*

# Installed from the lock file before the rest of the source is copied, so
# this (slow) layer stays cached across ordinary source edits.
COPY m8flow-telemetry /m8flow-telemetry
COPY m8flow-connector-proxy/pyproject.toml m8flow-connector-proxy/poetry.lock m8flow-connector-proxy/README.md ./
RUN --mount=type=cache,target=/root/.cache/pypoetry \
    poetry check --lock \
    && poetry install --no-interaction --no-root --sync

COPY m8flow-connector-proxy/ ./
RUN chmod +x bin/*

CMD ["./bin/run_server_locally"]
